<?php

class Core
{
    private static $url = 'http://shigeru-or-night.com/';
    private static $title = '【SHIGERU or NIGHT | 夜かと思ったら松崎しげるだった】';

    public static function getUrlWithQuery($str)
    {
        return self::$url . "?q=" . self::convStrToTitle($str);
    }

    public static function getUrl()
    {
        return self::$url;
    }

    public static function getText($file)
    {
        $text = "question, \r
Generated by http://fukase-no-owari.net \r
" . RedisController::getValue($file) . "
#フカセ暗号ジェネレーター";
        return urlencode($text);
    }

    public static function getTitle()
    {
        return self::$title;
    }
}
